Models/ErrorViewModel.cs
namespace UzMovie.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Movie.cs
public class Movie
{
   public int Id { get ; set; }
   public string Name { get ; set; }
   public int Year { get ; set; }
   public string Country { get ; set; }
   
}

Models/User.cs
public class User
{
    public int Id { get ; set ; }
    public string Name { get ; set ; }
    public string PhoneNumber { get ; set ; }
    public string Password { get ; set ; }
}

Models/UzMovie.cs
namespace UzMovie.Models;
public class UzMovie
{
   public int Id { get ; set; }
   public string Name { get ; set; }
   public int Year { get ; set; }
   public string Country { get ; set; }
   
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using UzMovie.Models;

namespace UzMovie.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;

namespace UzMovie.Controllers;

public class MovieController : Controller
{
    private readonly DataContext dbContext;
    
    public MovieController(DataContext dataContext)
    {
        this.dbContext=dataContext;
    }
    public IActionResult Index()
    {
        List<Movie> movies = new List<Movie>();
        movies = dbContext.Movies.ToList();

        return View(movies);
      
    }

    [HttpGet]
    public IActionResult Create()
    {
        
        return View();
    }

    [HttpPost]

    public IActionResult Store(Movie movie)
    {
        dbContext.Movies.Add(movie);
        dbContext.SaveChanges();
        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("[controller]/[action]/{id}")]
    public IActionResult Edit(int id)
    {
        var movie = dbContext.Movies.Find(id);
        return View(movie);
    }
    
    [HttpPost]
    [Route("[controller]/[action]/{id}")]
    public IActionResult Update(int id, Movie newmovie)
    {
        var oldmovie = dbContext.Movies.Find(id);

        oldmovie.Name = newmovie.Name;
        oldmovie.Year = newmovie.Year;
        oldmovie.Country = newmovie.Country;

        dbContext.SaveChanges();

        return RedirectToAction("Index");
    }

    [HttpGet]
    [Route("[controller]/[action]/{id}")]
    public IActionResult Delete(int id)
    {
        var movie=dbContext.Movies.Find(id);
        dbContext.Movies.Remove(movie);
        dbContext.SaveChanges();

        return RedirectToAction("Index");
    }
} 

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace UzMovie.Controllers;

public class UserController : Controller
{
    private readonly DataContext dbContext;

    public UserController(DataContext dataContext)
    {
        this.dbContext=dataContext;
    }
    public IActionResult Index()
    {
        List<User> users = new List<User>();
        return View(users);
    }
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    [HttpPost]
    public IActionResult Store()
    {
        return RedirectToAction ("Index");
    }
    

}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Movie/Create.cshtml
@model Movie


<div class="row">
    <div class="col-8">
        <form asp-controller="Movie" asp-action="Store">
            <div class="mb-3">
                <label for="Name" class="form-label">Kino nomi:</label>
                <input type="text" name="Name" class="form-control">
            </div>
            <div class="mb-3">
                <label for="Year" class="form-label">Nechinchi yil:</label>
                <input type="year" name="Year" class="form-control">
            </div>
            <div class="mb-3">
                <label for="Country">Davlat:</label>
                <select name="Country" id="Country" class="form-select">
                    <option value="Uzbek">O'zbekiston</option>
                    <option selected value="USA">AQSH</option>
                    <option value="Rassia">Rossiya</option>
                    <option value="UK">Angliya</option>
                </select>
            </div>
            <button type="submit" class="btn btn-outline-danger">Добавить</button>
        </form>
    </div>
  
</div>

   

   

Views/Movie/Edit.cshtml
@model Movie


<div class="row">
    <div class="col-8">
        <form asp-controller="Movie" asp-action="Update" asp-route-id="@Model.Id" method="post">
            <div class="mb-3">
                <label for="Name" class="form-label">Kino nomi:</label>
                <input type="text" name="Name" class="form-control" value="@Model.Name">
            </div>
            <div class="mb-3">
                <label for="Year" class="form-label">Nechinchi yil:</label>
                <input type="year" name="Year" class="form-control" value="@Model.Year">
            </div>
            <div class="mb-3">
                <label for="Country">Davlat:</label>
                <select name="Country" id="Country" class="form-select">
                    @if(Model.Country== "Uzbek")
                    {
                        <option selected value="Uzbek">O'zbekiston</option>
                    }
                    else
                    {
                        <option value="Uzbek">O'zbekiston</option>
                    }
                    @if(Model.Country== "USA")
                    {
                        <option selected value="USA">AQSH</option>
                    }
                    else
                    {
                        <option value="USA">AQSH</option>
                    }
                    @if(Model.Country== "Rassia")
                    {
                        <option selected value="Rassia">Rossiya</option>
                    }
                    else
                    {
                        <option value="Rassia">Rossiya</option>
                    }
                    @if(Model.Country== "UK")
                    {
                        <option selected value="UK">Angliya</option>
                    }
                    else
                    {
                        <option value="UK">Angliya</option>
                    }    
            </div> 
        </form>
        <button class="btn btn-outline-danger" type="submit">Сохранить</button>
    </div>
</div>
 

Views/Movie/Index.cshtml
@model List<Movie> 

<table class="table">
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>Year</th>
        <th>Country</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    @foreach(var film in Model)
    {
    <tr>
        <td>@film.Id</td>
        <td>@film.Name</td>
        <td>@film.Year</td>
        <td>@film.Country</td>
        <td><a asp-controller="Movie" asp-action="Edit" asp-route-id="@film.Id">Изминеть</a></td>
        <td><a asp-controller="Movie" asp-action="Delete" asp-route-id="@film.Id">Удалить</a></td>
    </tr>
    }
   
</table>

<a asp-controller="Movie" asp-action="Create"><button class="btn btn-outline-primary">Create film</button></a>
<br>

<table class="table text-center">
    <tr>
        <th colspan="2">1</th>
        <th rowspan="6">3</th>
    </tr>
    <tr>
        <td>4</td>
        <td>5</td>
        
    </tr>
    <tr>
        <td>7</td>
        <td>8</td>
        <td>9</td>
    </tr>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UzMovie</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UzMovie.styles.css" asp-append-version="true" />
    <script src="https://kit.fontawesome.com/a35a4d318e.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UzMovie</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">UzMovies</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Create">Create film</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>
                          @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create"> Create user</a>
                        </li> *@
                    </ul> 
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UzMovie - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/Index.cshtml
@model List<User>;


<table>
    <tr>
        <th>Id</th>
        <th>Name</th>
        <th>PhoneNumber</th>
        <th>Password</th>
    </tr>
    @foreach(var user in Model)
    {
        <tr> 
            <td>@user.Id</td>
            <td>@user.Name</td>
            <td>@user.PhoneNumber</td>
            <td>@user.Password</td>
        </tr>
    }   
    
</table>